version: '3.8'

services:
  db:
    image: postgres:16
    container_name: contango-postgres
    restart: always
    environment:
      POSTGRES_USER: contango_user
      POSTGRES_PASSWORD: contango_password
      POSTGRES_DB: contangodb
    ports:
      - "5433:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  app:
    container_name: contango-app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgres://contango_user:contango_password@db:5432/contangodb
      NODE_ENV: production
      NEXT_PUBLIC_API_URL: http://localhost:3000/api

volumes:
  pgdata:
